# Project 1 : (SQL Querry)-IMDB Dataset Analysis

Dataset : /content/drive/MyDrive/Datasets

# Importing the libraries

In [ ]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sqlite3

1. Establish a connection to the SQLite database

In [ ]:
db = '/kaggle/input/imdb-sqlite-dataset/movies.sqlite'
sqliteConnection = sqlite3.connect(db)
cur = sqliteConnection.cursor()

2. Get all the data from the movies

In [ ]:
# Get all the data about movies
query='SELECT * FROM movies'
cur.execute(query)
movies = cur.fetchall()

# Displaying the movies data
movies

# movies DataFrame

In [ ]:
movies=pd.DataFrame(movies, columns=['id', 'original_title', 'budget', 'popularity', 'release_date',
'revenue', 'title', 'vote_average', 'vote_count', 'overview', 'tagline',
'uid', 'director_id' ])

# Displaying the movies DataFrame
movies

In [ ]:
movies.info()

3. Get all the data about directors

In [ ]:
# Get all the data about directors
query='SELECT * FROM directors'
cur.execute(query)
directors=cur.fetchall()

# Displaying the directors data
directors

# directors DataFrame

In [ ]:
# Creating a directors DataFrame
directors=pd.DataFrame(directors, columns=['name', 'id', 'gender', 'uid', 'department'])

# Displaying the directors DataFrame
directors

In [ ]:
directors.info()

# Analysis

4. Check how many movies are present in the IMDB table

In [ ]:
query='SELECT COUNT(title) FROM movies'
cur.execute(query)
count=cur.fetchall()

print(f"The number of movies in the IMDB database is : {count[0]}")

5. Find these 3 directors : James Cameron, Luc Besson, John Woo

In [ ]:
query='SELECT * FROM directors WHERE name IN ("James Cameron", "Luc Besson", "John Woo")'
cur.execute(query)
three_directors=cur.fetchall()

print(f"These 3 directors data are : { three_directors[0], three_directors[1], three_directors[2] }")

6. Find all the directors with name starting with Steven

In [ ]:
query='SELECT * FROM directors WHERE name LIKE "Steven%"'
cur.execute(query)
name_like=cur.fetchall()

print(f"The directors whose names start with Steven are : {name_like}")

7. Count the female directors

In [ ]:
query='SELECT COUNT(*) FROM directors WHERE gender=1'
cur.execute(query)
female_directors=cur.fetchall()    #1 is for female and 2 is for male

print(f"The number of female directors are : {female_directors[0][0]}")

8. Find the name of the 10th first women directors

In [ ]:
query='SELECT name FROM directors WHERE gender=1'
cur.execute(query)
tenth_female=cur.fetchall()

print(f"The 10th first female director is : {tenth_female[9][0]}")

9. What are the 3 most popular movies

In [ ]:
movies

In [ ]:
query='SELECT title FROM movies ORDER BY popularity DESC LIMIT 3'
cur.execute(query)
most_popular=cur.fetchall()

print(f"The 3 most popular movies are : {most_popular[0][0]}, {most_popular[1][0]} and {most_popular[2][0]}")

10. What are 3 most bankable movies

In [ ]:
query='SELECT title FROM movies ORDER BY budget DESC LIMIT 3'
cur.execute(query)
most_bankable=cur.fetchall()

print(f"The 3 most bankable movies are : {most_bankable[0][0]}, {most_bankable[1][0]} and {most_bankable[2][0]}")

11. What is the most awarded average vote movie since Jan 1st, 2000

In [ ]:
query='SELECT title FROM movies WHERE release_date > "2000-01-01" ORDER BY vote_average DESC LIMIT 1'
cur.execute(query)
most_awarded=cur.fetchall()

print(f"The most awarded average vote movie is : {most_awarded[0][0]}")

# JOINS

12. Which movie(s) were directed by Brenda Chapman

In [ ]:
query='SELECT title FROM movies JOIN directors ON movies.director_id=directors.id WHERE directors.name="Brenda Chapman"'
cur.execute(query)
directed_by=cur.fetchall()

print(f"The movie directed by Brenda Chapman is : {directed_by[0][0]}")

13. Name of the director who has made the most movies

In [ ]:
query='SELECT name FROM directors as d INNER JOIN movies as m ON d.id=m.director_id GROUP BY m.director_id ORDER BY COUNT(d.name) DESC LIMIT 1'
cur.execute(query)
most_directed=cur.fetchall()

print(f"The directed who has made the most movies is : {most_directed[0][0]}")

14. Name of the director who is most bankable

In [ ]:
query='SELECT name FROM directors JOIN movies ON directors.id=movies.director_id GROUP BY movies.director_id ORDER BY SUM(budget) DESC LIMIT 1'
cur.execute(query)
most_bankable=cur.fetchall()

print(f"The directed who is most bankable is : {most_bankable[0][0]}")

# Budget Analysis

1. Find the top 10 highest budget movies

In [ ]:
query='SELECT * FROM movies ORDER BY budget DESC'
cur.execute(query)
top_10_budget=cur.fetchmany(size=10)

# Top 10 highest budget movies DataFrame
top_10_budget_df = pd.DataFrame(top_10_budget, columns=['id', 'original_title', 'budget', 'popularity', 'release_date', 'revenue',
       'title', 'vote_average', 'vote_count', 'overview', 'tagline', 'uid',
       'director_id'])

top_10_budget_df

# Revenue Analysis

1. Find the top 10 highest revenue making movies

In [ ]:
query='SELECT * FROM movies ORDER BY revenue DESC LIMIT 10'
cur.execute(query)
top_10_revenue=cur.fetchall()

# Top 10 highest revenue making movies DataFrame
top_10_revenue_df = pd.DataFrame(top_10_revenue, columns=['id', 'original_title', 'budget', 'popularity', 'release_date', 'revenue',
       'title', 'vote_average', 'vote_count', 'overview', 'tagline', 'uid',
       'director_id'])

top_10_revenue_df

# Vote Analysis

1. Find the most popular movies with the highest vote_average

In [ ]:
query='SELECT * FROM movies ORDER BY vote_average DESC'
cur.execute(query)
top_10_vote_average=cur.fetchmany(size=10)

# Top 10 highest vote_average movies DataFrame
top_10_vote_average_df = pd.DataFrame(top_10_vote_average, columns=['id', 'original_title', 'budget', 'popularity', 'release_date', 'revenue',
       'title', 'vote_average', 'vote_count', 'overview', 'tagline', 'uid',
       'director_id'])

top_10_vote_average_df

# Director Analysis

1. Name all the directors with the number of movies and the revenue. Sort by revenue

In [ ]:
query='SELECT name, COUNT(movies.title) AS Total_Movies, SUM(revenue) AS Total_Revenue FROM movies INNER JOIN directors ON movies.director_id=directors.id GROUP BY movies.director_id ORDER BY SUM(revenue) DESC'
cur.execute(query)
director_revenue=cur.fetchall()

director_revenue_df = pd.DataFrame(director_revenue, columns=["Name", "Total_Movies", "Total_Revenue"])
director_revenue_df

2. Name all the directors with the number of movies and the revenue.
Sort by number of movies

In [ ]:
query='SELECT name, COUNT(movies.title) AS Total_Movies, SUM(revenue) AS Total_Revenue FROM movies INNER JOIN directors ON movies.director_id=directors.id GROUP BY movies.director_id ORDER BY COUNT(movies.title) DESC'
cur.execute(query)
director_movies=cur.fetchall()

director_movies_df = pd.DataFrame(director_movies, columns=["Name", "Total_Movies", "Total_Revenue"])
director_movies_df

3. Give the title, release date, budget, revenue, populartity and vote average of movies made by Steven Spielberg

In [ ]:
query='SELECT title, release_date, budget, revenue, popularity, vote_average FROM movies INNER JOIN directors ON movies.director_id=directors.id WHERE directors.name="Steven Spielberg"'
cur.execute(query)
Steven_movies=cur.fetchall()

Steven_movies_df = pd.DataFrame(Steven_movies, columns=["title", "release_date", "budget", "revenue", "popularity", "vote_average"])
Steven_movies_df